---
- name: copybin reatime svr
  hosts: all
  become: yes
  tasks:
    - debug: msg="start copybin reatime svr"

    - local_action: stat path=/opt/tmp/{{newpkg}}
      register: newpkg_exist
      debug: msg="{{newpkg_exist.stdout}}"
